### ISSUE TITLE
Warning: array_merge(): Argument #1 is not an array in src/includes/functions/utils.php on line 81

### ISSUE THREAD

**Issue by raamdev** [websharks/wp-php-rv#12]
Got this while testing the WooCommerce Intercom plugin... not sure if this is a false-positive or an actual bug, but I'm opening an issue just in case. It looks like WooCommerce Intercom is [configured](https://github.com/websharks/woocommerce-intercom-pro/blob/dev/composer.json#L31) to use the `dev` version of WP PHP RV, which is a bad thing (i.e., it's using an unreleased version). I see this was inherited from the WP Sharks Skeleton repo, which is [also configured](https://github.com/websharks/wp-sharks-skeleton-pro/blob/dev/composer.json#L31) to have Composer install the dev version.

```
( ! ) Warning: array_merge(): Argument #1 is not an array in /srv/www/wordpress-default/wp-content/plugins/woocommerce-intercom-pro/src/vendor/websharks/wp-php-rv/src/includes/functions/utils.php on line 81
Call Stack
#	Time	Memory	Function	Location
1	0.2143	363648	{main}( )	.../plugin-install.php:0
2	0.2155	364320	require_once( '/srv/www/wordpress-default/wp-admin/admin.php' )	.../plugin-install.php:15
3	0.2162	364800	require_once( '/srv/www/wordpress-default/wp-load.php' )	.../admin.php:31
4	0.2168	365600	require_once( '/srv/www/wordpress-default/wp-config.php' )	.../wp-load.php:39
5	0.2171	367000	require_once( '/srv/www/wordpress-default/wp-settings.php' )	.../wp-config.php:56
6	0.3699	2980208	include_once( '/srv/www/wordpress-default/wp-content/plugins/wp-sharks-core/plugin.php' )	.../wp-settings.php:273
7	0.3748	2980856	require( '/srv/www/wordpress-default/wp-content/plugins/wp-sharks-core/src/vendor/websharks/wp-php-rv/src/includes/check.php' )	.../plugin.php:27
8	0.3748	2980480	wp_php_rv( )	.../check.php:17
9	0.3748	2980480	___wp_php_rv_issue( )	.../checks.php:20
10	0.3748	2980480	___wp_php_rv_can_call_func( string(4) )	.../checks.php:61
11	0.3749	2983576	array_merge ( null, array(21) )	.../utils.php:81
```

**Comment by jaswsinc** [comment]
Next Release Changelog:

- Bug fix. Array not initialized properly. See: #12

**Comment by jaswsinc** [comment]
@raamdev Nice catch. Thanks for reporting!

Regarding `dev-master`. That's configured to pull the `master` branch and not the `dev` branch. The Packagist system considers `master` to be a `dev-` tag, and so it's a bit confusing when you glance over the `composer.json` file. However, that's pulling the `master` branch.
